// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDc2jjmSlnklClOvdYEZlf1ByJLnJ-yFI',
    appId: '1:566885799035:web:6da101b038ad6b032bfede',
    messagingSenderId: '566885799035',
    projectId: 'examcheck-app',
    authDomain: 'examcheck-app.firebaseapp.com',
    storageBucket: 'examcheck-app.firebasestorage.app',
    measurementId: 'G-PM5V5CRJW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1yVZoRcVWE-5ge_rvRGUqDXmYBVW3rZk',
    appId: '1:566885799035:android:c49bc8bd25d3c3d82bfede',
    messagingSenderId: '566885799035',
    projectId: 'examcheck-app',
    storageBucket: 'examcheck-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRgXSudCRB73sBXOeh1tIJ_x7c6vYzLhE',
    appId: '1:566885799035:ios:c76096e0dcb3b1fe2bfede',
    messagingSenderId: '566885799035',
    projectId: 'examcheck-app',
    storageBucket: 'examcheck-app.firebasestorage.app',
    iosBundleId: 'com.example.examcheckApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRgXSudCRB73sBXOeh1tIJ_x7c6vYzLhE',
    appId: '1:566885799035:ios:c76096e0dcb3b1fe2bfede',
    messagingSenderId: '566885799035',
    projectId: 'examcheck-app',
    storageBucket: 'examcheck-app.firebasestorage.app',
    iosBundleId: 'com.example.examcheckApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDc2jjmSlnklClOvdYEZlf1ByJLnJ-yFI',
    appId: '1:566885799035:web:b77674908c6c2e152bfede',
    messagingSenderId: '566885799035',
    projectId: 'examcheck-app',
    authDomain: 'examcheck-app.firebaseapp.com',
    storageBucket: 'examcheck-app.firebasestorage.app',
    measurementId: 'G-VSTEK5JJPG',
  );
}
